# Generated by Django 5.2 on 2025-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'AUDI'), (3, 'AUDI'), (4, 'AUDI'), (5, 'AUDI'), (6, 'AUDI'), (7, 'AUDI'), (8, 'AUDI'), (9, 'AUDI')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'BRANCO'), (1, 'AZUL'), (1, 'VERMELHO'), (1, 'PRETO'), (1, 'PRATA')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'ETANOL'), (1, 'DIESEL'), (1, 'FLEX'), (1, 'GASOLINA')])),
            ],
        ),
    ]
